# 📊 Pandas EAD 1 - Introdução ao Pandas

Este notebook é uma introdução à biblioteca **Pandas**, a ferramenta mais poderosa para análise de dados em Python.

## 📚 Conceitos abordados:
- O que é o Pandas?
- Instalação e importação
- Estruturas principais: Series e DataFrame
- Criando DataFrames
- Visualizando dados
- Selecionando colunas
- Estatísticas básicas

## 🎯 Objetivo:
Ao final deste módulo, você será capaz de criar e manipular DataFrames básicos no Pandas.

**Vamos começar!** 🚀

## 1. O que é o Pandas?

Pandas é uma biblioteca Python que fornece estruturas de dados de alta performance e ferramentas de análise de dados.

### Principais estruturas:

1. **Series**: Array unidimensional (uma coluna)
2. **DataFrame**: Estrutura bidimensional (tabela com linhas e colunas)

### Por que usar Pandas?
- ✅ Fácil manipulação de dados tabulares
- ✅ Leitura/escrita de diversos formatos (CSV, Excel, SQL, JSON)
- ✅ Limpeza e preparação de dados
- ✅ Análise estatística rápida
- ✅ Integração com outras bibliotecas (NumPy, Matplotlib)

## 2. Instalação e Importação

### Instalação (se necessário):
```bash
pip install pandas
```

### Importação:
O padrão é importar o pandas como `pd`:

In [4]:
import pandas as pd

# Verificando a versão
print(f"Versão do Pandas: {pd.__version__}")

Versão do Pandas: 3.0.5

## 3. Series - A Estrutura Unidimensional

Uma Series é como uma coluna de dados. Pode ser criada a partir de uma lista, dicionário ou array NumPy.

In [5]:
# Criando uma Series a partir de uma lista
notas = pd.Series([8, 9, 7, 10, 6])
print(notas)
print("\n" + "="*40)
print(f"Média: {notas.mean()}")
print(f"Máximo: {notas.max()}")
print(f"Mínimo: {notas.min()}")

0     8
1     9
2     7
3    10
4     6
dtype: int64

========================================
Média: 8.0
Máximo: 10
Mínimo: 6

## 4. DataFrame - A Estrutura Bidimensional

Um DataFrame é como uma planilha ou tabela SQL. É a estrutura mais usada no Pandas.

In [6]:
# Criando um DataFrame a partir de um dicionário
dados = {
    'Nome': ['Ana', 'João', 'Maria', 'Pedro', 'Carla'],
    'Idade': [25, 30, 28, 35, 22],
    'Cidade': ['São Paulo', 'Rio', 'Belo Horizonte', 'Curitiba', 'Salvador'],
    'Nota': [8.5, 9.0, 7.5, 9.5, 8.0]
}

df = pd.DataFrame(dados)
print(df)

    Nome  Idade          Cidade  Nota
0    Ana     25       São Paulo   8.5
1   João     30             Rio   9.0
2  Maria     28  Belo Horizonte   7.5
3  Pedro     35        Curitiba   9.5
4  Carla     22        Salvador   8.0

## 5. Visualizando Dados

O Pandas oferece várias formas de visualizar os dados:

In [7]:
# Visualizando as primeiras linhas
print("Primeiras 3 linhas:")
print(df.head(3))

print("\nÚltimas 2 linhas:")
print(df.tail(2))

print("\nInformações do DataFrame:")
print(df.info())

print("\nEstatísticas descritivas:")
print(df.describe())

Primeiras 3 linhas:
    Nome  Idade          Cidade  Nota
0    Ana     25       São Paulo   8.5
1   João     30             Rio   9.0
2  Maria     28  Belo Horizonte   7.5

Últimas 2 linhas:
    Nome  Idade    Cidade  Nota
3  Pedro     35  Curitiba   9.5
4  Carla     22  Salvador   8.0

Informações do DataFrame:
<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Nome    5 non-null      str
 1   Idade   5 non-null      int64
 2   Cidade  5 non-null      str
 3   Nota    5 non-null      float64
dtypes: float64(1), int64(1), str(2)
memory usage: 358.0 bytes
None

Estatísticas descritivas:
           Idade      Nota
count   5.000000  5.000000
mean   28.000000  8.500000
std     4.949747  0.790569
min    22.000000  7.500000
25%    25.000000  8.000000
50%    28.000000  8.500000
75%    30.000000  9.000000
max    35.000000  9.500000

## 6. Selecionando Colunas

Você pode selecionar colunas de várias formas:

In [8]:
# Selecionando uma coluna (retorna uma Series)
print("Coluna Nome:")
print(df['Nome'])

print("\nMúltiplas colunas (retorna um DataFrame):")
print(df[['Nome', 'Nota']])

Coluna Nome:
0      Ana
1     João
2    Maria
3    Pedro
4    Carla
Name: Nome, dtype: str

Múltiplas colunas (retorna um DataFrame):
    Nome  Nota
0    Ana   8.5
1   João   9.0
2  Maria   7.5
3  Pedro   9.5
4  Carla   8.0

## 7. Adicionando Nova Coluna

É muito fácil adicionar novas colunas a um DataFrame:

In [9]:
# Adicionando uma coluna de status (aprovado/reprovado)
df['Status'] = df['Nota'].apply(lambda x: 'Aprovado' if x >= 7 else 'Reprovado')
print(df)

    Nome  Idade          Cidade  Nota    Status
0    Ana     25       São Paulo   8.5  Aprovado
1   João     30             Rio   9.0  Aprovado
2  Maria     28  Belo Horizonte   7.5  Aprovado
3  Pedro     35        Curitiba   9.5  Aprovado
4  Carla     22        Salvador   8.0  Aprovado

## 8. Exercícios - Nível 1

Agora é sua vez! Resolva os exercícios abaixo para fixar os conceitos básicos do Pandas.

### Exercício 1: Criando um DataFrame
Crie um DataFrame com os seguintes dados de produtos:
- Produtos: ['Notebook', 'Mouse', 'Teclado', 'Monitor', 'Headset']
- Preços: [2500, 80, 200, 1200, 300]
- Quantidade: [10, 50, 30, 15, 40]

Calcule o valor total em estoque (preço * quantidade) para cada produto e adicione como uma nova coluna.

In [26]:
# Seu código aqui

dados = {
    'Produtos': ['Notebook', 'Mouse', 'Teclado', 'Monitor', 'Headset'],
    'Preços': [2500, 80, 200, 1200, 300],
    'Quantidade': [10,50,30,15,40]
}

df = pd.DataFrame(dados)
valor_total_estoque = (df['Preços'] * df['Quantidade']).sum()

print(f"O valor total em estoque é:R${valor_total_estoque}")

O valor total em estoque é:R$65000

### Exercício 2: Visualizando Dados
Use o DataFrame criado no exercício anterior e:
1. Mostre as 3 primeiras linhas
2. Mostre as estatísticas descritivas
3. Mostre apenas os produtos com preço > 500

In [33]:
# Seu código aqui
df.head(3)

df.describe()


produtos_5000 = df[df['Preços'] >= 5000]

print(df[df['Preços'] >= 500])

   Produtos  Preços  Quantidade
0  Notebook    2500          10
3   Monitor    1200          15

### Exercício 3: Series e Métodos Básicos
Crie uma Series com as idades de 10 pessoas. Calcule e imprima:
- Média das idades
- Mediana
- Desvio padrão
- Idade máxima e mínima
- Número total de elementos

In [48]:
# Seu código aqui
idades = pd.Series(
    [18, 20, 25, 17, 30, 22, 19, 35, 28, 21],
    index=['Gabi', 'Bell', 'Pedro', 'Ana', 'Lucas',
           'Julia', 'Carlos', 'Beatriz', 'Keila', 'Larissa']
)

idades.describe().round(2)

count    10.00
mean     23.50
std       5.87
min      17.00
25%      19.25
50%      21.50
75%      27.25
max      35.00
dtype: float64

### Exercício 4: DataFrame a partir de Lista
Crie um DataFrame a partir de uma lista de listas:
```python
dados = [
    ['Ana', 25, 'SP', 8.5],
    ['João', 30, 'RJ', 9.0],
    ['Maria', 28, 'BH', 7.5]
]
```
Defina os nomes das colunas como ['Nome', 'Idade', 'Cidade', 'Nota'].

In [63]:
# Seu código aqui
dados = [

['Ana',25,'SP', 8.5],
['João', 30, 'RJ', 90],
['Maria', 28, 'BH', 7.5]


]
df = pd.DataFrame(dados)

colunas  = df.columns = ['Nome','idade','Cidade','Nota']

print(colunas)

['Nome', 'idade', 'Cidade', 'Nota']

### Exercício 5: Adicionando Colunas
Baseado no DataFrame do exercício 4, adicione:
1. Uma coluna 'Dobro da Idade'
2. Uma coluna 'Nota + 1'

In [64]:
df

    Nome  idade Cidade  Nota
0    Ana     25     SP   8.5
1   João     30     RJ  90.0
2  Maria     28     BH   7.5

In [65]:
# Seu código aqui

df['Dobro da Idade'] = df['idade'] * 2
df['Nota a mais'] = df['Nota']+1
df

    Nome  idade Cidade  Nota  Dobro da Idade  Nota a mais
0    Ana     25     SP   8.5              50          9.5
1   João     30     RJ  90.0              60         91.0
2  Maria     28     BH   7.5              56          8.5